version: '3.8'
services:
  # react:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile 
  #   ports:
  #     - '3000:3000'
  #   tty: true
  #   stdin_open: true




  go:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: go-api
    environment:
      - Asia/Tokyo
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./backend/:/app
      - .env:/app/.env
    networks:
      - default
  db:
    container_name: db
    build: 
     context: .
     dockerfile: ./backend/db/Dockerfile
    tty: true
    ports:
     - 3306:3306
    environment:
     TZ: Asia/Tokyo
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     MYSQL_DATABASE: ${MYSQL_DATABASE}
     MYSQL_USER:  ${MYSQL_USER}
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
     - mysql-local:/var/lib/mysql
     - ./backend/db/initdb.d:/docker-entrypoint-initdb.d/
    networks:
     - default
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
networks:
 default:
volumes:
  mysql-local: # 名前付きボリュームを定義

