import React, { ReactElement } from 'react'

import Head from 'next/head'
import Navbar from '../elements/Navbar'
import { Box } from '@chakra-ui/react'


type LayoutProps = Required<{
    readonly children: ReactElement
  }>

function Layout({ children }: LayoutProps) {
  return (
<>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
          </Head>
          
    <div>
              <Navbar />
             
        {children}

              </div>
               

    </>
    
  )
}

export default Layout